<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prices.proto

namespace Magento\PricingStorefrontApi\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>magento.pricingStorefrontApi.proto.PriceBookUnassignPricesResponse</code>
 */
class PriceBookUnassignPricesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.magento.pricingStorefrontApi.proto.Status status = 1;</code>
     */
    protected $status = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Magento\PricingStorefrontApi\Proto\Status $status
     * }
     */
    public function __construct($data = null)
    {
        \Magento\PricingStorefrontApi\Metadata\Prices::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.magento.pricingStorefrontApi.proto.Status status = 1;</code>
     * @return \Magento\PricingStorefrontApi\Proto\Status
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.magento.pricingStorefrontApi.proto.Status status = 1;</code>
     * @param \Magento\PricingStorefrontApi\Proto\Status $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Magento\PricingStorefrontApi\Proto\Status::class);
        $this->status = $var;

        return $this;
    }
}
