<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prices.proto

namespace Magento\PricingStorefrontApi\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>magento.pricingStorefrontApi.proto.PriceBook</code>
 */
class PriceBook extends \Google\Protobuf\Internal\Message
{
    /**
     * Price book ID. Can be requested via findPriceBook service
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Price book name (e.g. "10% off on selected products")
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Parent Price Book Id.
     * Used to build fallback system and find price in parent price book if price not present in requested price book
     *
     * Generated from protobuf field <code>string parent_id = 3;</code>
     */
    protected $parent_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           Price book ID. Can be requested via findPriceBook service
     *     @type string $name
     *           Price book name (e.g. "10% off on selected products")
     *     @type string $parent_id
     *           Parent Price Book Id.
     *           Used to build fallback system and find price in parent price book if price not present in requested price book
     * }
     */
    public function __construct($data = null)
    {
        \Magento\PricingStorefrontApi\Metadata\Prices::initOnce();
        parent::__construct($data);
    }

    /**
     * Price book ID. Can be requested via findPriceBook service
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Price book ID. Can be requested via findPriceBook service
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * Price book name (e.g. "10% off on selected products")
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Price book name (e.g. "10% off on selected products")
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Parent Price Book Id.
     * Used to build fallback system and find price in parent price book if price not present in requested price book
     *
     * Generated from protobuf field <code>string parent_id = 3;</code>
     * @return string
     */
    public function getParentId()
    {
        return $this->parent_id;
    }

    /**
     * Parent Price Book Id.
     * Used to build fallback system and find price in parent price book if price not present in requested price book
     *
     * Generated from protobuf field <code>string parent_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setParentId($var)
    {
        GPBUtil::checkString($var, true);
        $this->parent_id = $var;

        return $this;
    }
}
