<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prices.proto

namespace Magento\PricingStorefrontApi\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>magento.pricingStorefrontApi.proto.Price</code>
 */
class Price extends \Google\Protobuf\Internal\Message
{
    /**
     * Price without applied discounts. E.g. regular price of variation for Configurable product or regular price for Simple product
     *
     * Generated from protobuf field <code>float regular = 1;</code>
     */
    protected $regular = 0.0;
    /**
     * Final price with applied discounts. E.g. final price of variation for Configurable product
     *
     * Generated from protobuf field <code>float final = 2;</code>
     */
    protected $final = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $regular
     *           Price without applied discounts. E.g. regular price of variation for Configurable product or regular price for Simple product
     *     @type float $final
     *           Final price with applied discounts. E.g. final price of variation for Configurable product
     * }
     */
    public function __construct($data = null)
    {
        \Magento\PricingStorefrontApi\Metadata\Prices::initOnce();
        parent::__construct($data);
    }

    /**
     * Price without applied discounts. E.g. regular price of variation for Configurable product or regular price for Simple product
     *
     * Generated from protobuf field <code>float regular = 1;</code>
     * @return float
     */
    public function getRegular()
    {
        return $this->regular;
    }

    /**
     * Price without applied discounts. E.g. regular price of variation for Configurable product or regular price for Simple product
     *
     * Generated from protobuf field <code>float regular = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setRegular($var)
    {
        GPBUtil::checkFloat($var);
        $this->regular = $var;

        return $this;
    }

    /**
     * Final price with applied discounts. E.g. final price of variation for Configurable product
     *
     * Generated from protobuf field <code>float final = 2;</code>
     * @return float
     */
    public function getFinal()
    {
        return $this->final;
    }

    /**
     * Final price with applied discounts. E.g. final price of variation for Configurable product
     *
     * Generated from protobuf field <code>float final = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setFinal($var)
    {
        GPBUtil::checkFloat($var);
        $this->final = $var;

        return $this;
    }
}
