<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prices.proto

namespace Magento\PricingStorefrontApi\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>magento.pricingStorefrontApi.proto.PriceBookScopeRequest</code>
 */
class PriceBookScopeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.magento.pricingStorefrontApi.proto.Scope scope = 1;</code>
     */
    protected $scope = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Magento\PricingStorefrontApi\Proto\Scope $scope
     * }
     */
    public function __construct($data = null)
    {
        \Magento\PricingStorefrontApi\Metadata\Prices::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.magento.pricingStorefrontApi.proto.Scope scope = 1;</code>
     * @return \Magento\PricingStorefrontApi\Proto\Scope
     */
    public function getScope()
    {
        return $this->scope;
    }

    /**
     * Generated from protobuf field <code>.magento.pricingStorefrontApi.proto.Scope scope = 1;</code>
     * @param \Magento\PricingStorefrontApi\Proto\Scope $var
     * @return $this
     */
    public function setScope($var)
    {
        GPBUtil::checkMessage($var, \Magento\PricingStorefrontApi\Proto\Scope::class);
        $this->scope = $var;

        return $this;
    }
}
