<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\PricingStorefrontApi\Api\Data;

/**
 * Autogenerated description for AssignPricesRequest class
 *
 * phpcs:disable Magento2.PHP.FinalImplementation
 * @SuppressWarnings(PHPMD)
 * @SuppressWarnings(PHPCPD)
 */
final class AssignPricesRequest implements AssignPricesRequestInterface
{

    /**
     * @var array
     */
    private $prices;

    /**
     * @var string
     */
    private $priceBookId;
    
    /**
     * @inheritdoc
     *
     * @return \Magento\PricingStorefrontApi\Api\Data\ProductPriceInterface[]
     */
    public function getPrices(): array
    {
        return (array) $this->prices;
    }
    
    /**
     * @inheritdoc
     *
     * @param \Magento\PricingStorefrontApi\Api\Data\ProductPriceInterface[] $value
     * @return void
     */
    public function setPrices(array $value): void
    {
        $this->prices = $value;
    }
    
    /**
     * @inheritdoc
     *
     * @return string
     */
    public function getPriceBookId(): string
    {
        return (string) $this->priceBookId;
    }
    
    /**
     * @inheritdoc
     *
     * @param string $value
     * @return void
     */
    public function setPriceBookId(string $value): void
    {
        $this->priceBookId = $value;
    }
}
