<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\PricingStorefrontApi\Api\Data;

/**
 * Autogenerated description for GetPricesOutput interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface GetPricesOutputInterface
{
    /**
     * Autogenerated description for getPrices() interface method
     *
     * @return \Magento\PricingStorefrontApi\Api\Data\ProductPriceInterface[]
     */
    public function getPrices(): array;

    /**
     * Autogenerated description for setPrices() interface method
     *
     * @param \Magento\PricingStorefrontApi\Api\Data\ProductPriceInterface[] $value
     * @return void
     */
    public function setPrices(array $value): void;
}
