<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\PricingStorefrontApi\Api\Data;

/**
 * Autogenerated description for Price class
 *
 * phpcs:disable Magento2.PHP.FinalImplementation
 * @SuppressWarnings(PHPMD)
 * @SuppressWarnings(PHPCPD)
 */
final class Price implements PriceInterface
{

    /**
     * @var float
     */
    private $regular;

    /**
     * @var float
     */
    private $final;
    
    /**
     * @inheritdoc
     *
     * @return float
     */
    public function getRegular(): float
    {
        return (float) $this->regular;
    }
    
    /**
     * @inheritdoc
     *
     * @param float $value
     * @return void
     */
    public function setRegular(float $value): void
    {
        $this->regular = $value;
    }
    
    /**
     * @inheritdoc
     *
     * @return float
     */
    public function getFinal(): float
    {
        return (float) $this->final;
    }
    
    /**
     * @inheritdoc
     *
     * @param float $value
     * @return void
     */
    public function setFinal(float $value): void
    {
        $this->final = $value;
    }
}
