<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\PricingStorefrontApi\Api\Data;

/**
 * Autogenerated description for PriceBook interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface PriceBookInterface
{
    /**
     * Autogenerated description for getId() interface method
     *
     * @return string
     */
    public function getId(): string;

    /**
     * Autogenerated description for setId() interface method
     *
     * @param string $value
     * @return void
     */
    public function setId(string $value): void;

    /**
     * Autogenerated description for getName() interface method
     *
     * @return string
     */
    public function getName(): string;

    /**
     * Autogenerated description for setName() interface method
     *
     * @param string $value
     * @return void
     */
    public function setName(string $value): void;

    /**
     * Autogenerated description for getParentId() interface method
     *
     * @return string
     */
    public function getParentId(): string;

    /**
     * Autogenerated description for setParentId() interface method
     *
     * @param string $value
     * @return void
     */
    public function setParentId(string $value): void;

    /**
     * Autogenerated description for getScope() interface method
     *
     * @return \Magento\PricingStorefrontApi\Api\Data\ScopeInterface|null
     */
    public function getScope(): ?\Magento\PricingStorefrontApi\Api\Data\ScopeInterface;

    /**
     * Autogenerated description for setScope() interface method
     *
     * @param \Magento\PricingStorefrontApi\Api\Data\ScopeInterface $value
     * @return void
     */
    public function setScope(\Magento\PricingStorefrontApi\Api\Data\ScopeInterface $value): void;
}
