<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\PricingStorefrontApi\Api\Data;

/**
 * Autogenerated description for PriceBookScopeRequest interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface PriceBookScopeRequestInterface
{
    /**
     * Autogenerated description for getScopes() interface method
     *
     * @return \Magento\PricingStorefrontApi\Api\Data\ScopeInterface|null
     */
    public function getScope(): ?\Magento\PricingStorefrontApi\Api\Data\ScopeInterface;

    /**
     * Autogenerated description for setScopes() interface method
     *
     * @param \Magento\PricingStorefrontApi\Api\Data\ScopeInterface $value
     * @return void
     */
    public function setScopes(\Magento\PricingStorefrontApi\Api\Data\ScopeInterface $value): void;
}
