<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\PricingStorefrontApi\Api\Data;

use Magento\Framework\ObjectManagerInterface;

/**
 * Autogenerated description for PriceBookCreateRequest class
 *
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 * @SuppressWarnings(PHPMD.CyclomaticComplexity)
 * @SuppressWarnings(PHPMD.UnusedPrivateField)
 * @SuppressWarnings(PHPMD.NPathComplexity)
 * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
 */
final class PriceBookCreateRequestArrayMapper
{
    /**
     * @var mixed
     */
    private $data;

    /**
     * @var ObjectManagerInterface
     */
    private $objectManager;

    public function __construct(ObjectManagerInterface $objectManager)
    {
        $this->objectManager = $objectManager;
    }

    /**
    * Convert the DTO to the array with the data
    *
    * @param PriceBookCreateRequest $dto
    * @return array
    */
    public function convertToArray(PriceBookCreateRequest $dto)
    {
        $result = [];
        $result["name"] = $dto->getName();
        $result["parent_id"] = $dto->getParentId();
        if ($dto->getScope() !== null) {
            $result["scope"] = $this->objectManager->get(\Magento\PricingStorefrontApi\Api\Data\ScopeArrayMapper::class)
                ->convertToArray($dto->getScope());
        }
        return $result;
    }
}
