<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\PricingStorefrontApi\Api\Data;

/**
 * Autogenerated description for PriceBookCreateResponse class
 *
 * phpcs:disable Magento2.PHP.FinalImplementation
 * @SuppressWarnings(PHPMD)
 * @SuppressWarnings(PHPCPD)
 */
final class PriceBookCreateResponse implements PriceBookCreateResponseInterface
{

    /**
     * @var \Magento\PricingStorefrontApi\Api\Data\PriceBookInterface
     */
    private $priceBook;

    /**
     * @var \Magento\PricingStorefrontApi\Api\Data\StatusInterface
     */
    private $status;
    
    /**
     * @inheritdoc
     *
     * @return \Magento\PricingStorefrontApi\Api\Data\PriceBookInterface|null
     */
    public function getPriceBook(): ?\Magento\PricingStorefrontApi\Api\Data\PriceBookInterface
    {
        return $this->priceBook;
    }
    
    /**
     * @inheritdoc
     *
     * @param \Magento\PricingStorefrontApi\Api\Data\PriceBookInterface $value
     * @return void
     */
    public function setPriceBook(\Magento\PricingStorefrontApi\Api\Data\PriceBookInterface $value): void
    {
        $this->priceBook = $value;
    }
    
    /**
     * @inheritdoc
     *
     * @return \Magento\PricingStorefrontApi\Api\Data\StatusInterface|null
     */
    public function getStatus(): ?\Magento\PricingStorefrontApi\Api\Data\StatusInterface
    {
        return $this->status;
    }
    
    /**
     * @inheritdoc
     *
     * @param \Magento\PricingStorefrontApi\Api\Data\StatusInterface $value
     * @return void
     */
    public function setStatus(\Magento\PricingStorefrontApi\Api\Data\StatusInterface $value): void
    {
        $this->status = $value;
    }
}
