<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\PricingStorefrontApi\Api\Data;

/**
 * Autogenerated description for PriceBook class
 *
 * phpcs:disable Magento2.PHP.FinalImplementation
 * @SuppressWarnings(PHPMD)
 * @SuppressWarnings(PHPCPD)
 */
final class PriceBook implements PriceBookInterface
{

    /**
     * @var string
     */
    private $id;

    /**
     * @var string
     */
    private $name;

    /**
     * @var string
     */
    private $parentId;

    /**
     * @var \Magento\PricingStorefrontApi\Api\Data\ScopeInterface
     */
    private $scope;
    
    /**
     * @inheritdoc
     *
     * @return string
     */
    public function getId(): string
    {
        return (string) $this->id;
    }
    
    /**
     * @inheritdoc
     *
     * @param string $value
     * @return void
     */
    public function setId(string $value): void
    {
        $this->id = $value;
    }
    
    /**
     * @inheritdoc
     *
     * @return string
     */
    public function getName(): string
    {
        return (string) $this->name;
    }
    
    /**
     * @inheritdoc
     *
     * @param string $value
     * @return void
     */
    public function setName(string $value): void
    {
        $this->name = $value;
    }
    
    /**
     * @inheritdoc
     *
     * @return string
     */
    public function getParentId(): string
    {
        return (string) $this->parentId;
    }
    
    /**
     * @inheritdoc
     *
     * @param string $value
     * @return void
     */
    public function setParentId(string $value): void
    {
        $this->parentId = $value;
    }
    
    /**
     * @inheritdoc
     *
     * @return \Magento\PricingStorefrontApi\Api\Data\ScopeInterface|null
     */
    public function getScope(): ?\Magento\PricingStorefrontApi\Api\Data\ScopeInterface
    {
        return $this->scope;
    }
    
    /**
     * @inheritdoc
     *
     * @param \Magento\PricingStorefrontApi\Api\Data\ScopeInterface $value
     * @return void
     */
    public function setScope(\Magento\PricingStorefrontApi\Api\Data\ScopeInterface $value): void
    {
        $this->scope = $value;
    }
}
