<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\PricingStorefrontApi\Api\Data;

/**
 * Autogenerated description for PriceBookAssignPricesResponse interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface PriceBookAssignPricesResponseInterface
{
    /**
     * Autogenerated description for getStatus() interface method
     *
     * @return \Magento\PricingStorefrontApi\Api\Data\StatusInterface|null
     */
    public function getStatus(): ?\Magento\PricingStorefrontApi\Api\Data\StatusInterface;

    /**
     * Autogenerated description for setStatus() interface method
     *
     * @param \Magento\PricingStorefrontApi\Api\Data\StatusInterface $value
     * @return void
     */
    public function setStatus(\Magento\PricingStorefrontApi\Api\Data\StatusInterface $value): void;
}
