<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\PricingStorefrontApi\Api\Data;

/**
 * Autogenerated description for Price interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface PriceInterface
{
    /**
     * Autogenerated description for getRegular() interface method
     *
     * @return float
     */
    public function getRegular(): float;

    /**
     * Autogenerated description for setRegular() interface method
     *
     * @param float $value
     * @return void
     */
    public function setRegular(float $value): void;

    /**
     * Autogenerated description for getFinal() interface method
     *
     * @return float
     */
    public function getFinal(): float;

    /**
     * Autogenerated description for setFinal() interface method
     *
     * @param float $value
     * @return void
     */
    public function setFinal(float $value): void;
}
