<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\PricingStorefrontApi\Api\Data;

use Magento\Framework\ObjectManagerInterface;

/**
 * Autogenerated description for ProductPrice class
 *
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 * @SuppressWarnings(PHPMD.CyclomaticComplexity)
 * @SuppressWarnings(PHPMD.UnusedPrivateField)
 * @SuppressWarnings(PHPMD.NPathComplexity)
 * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
 */
final class ProductPriceArrayMapper
{
    /**
     * @var mixed
     */
    private $data;

    /**
     * @var ObjectManagerInterface
     */
    private $objectManager;

    public function __construct(ObjectManagerInterface $objectManager)
    {
        $this->objectManager = $objectManager;
    }

    /**
    * Convert the DTO to the array with the data
    *
    * @param ProductPrice $dto
    * @return array
    */
    public function convertToArray(ProductPrice $dto)
    {
        $result = [];
        $result["entity_id"] = $dto->getEntityId();
        if ($dto->getMinimumPrice() !== null) {
            $result["minimum_price"] = $this->objectManager->get(\Magento\PricingStorefrontApi\Api\Data\PriceArrayMapper::class)
                ->convertToArray($dto->getMinimumPrice());
        }
        if ($dto->getMaximumPrice() !== null) {
            $result["maximum_price"] = $this->objectManager->get(\Magento\PricingStorefrontApi\Api\Data\PriceArrayMapper::class)
                ->convertToArray($dto->getMaximumPrice());
        }
        $result["qty"] = $dto->getQty();
        return $result;
    }
}
