<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\PricingStorefrontApi\Api\Data;

/**
 * Autogenerated description for Scope interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface ScopeInterface
{
    /**
     * Autogenerated description for getWebsite() interface method
     *
     * @return string[]
     */
    public function getWebsite(): array;

    /**
     * Autogenerated description for setWebsite() interface method
     *
     * @param string[] $value
     * @return void
     */
    public function setWebsite(array $value): void;

    /**
     * Autogenerated description for getCustomerGroup() interface method
     *
     * @return string[]
     */
    public function getCustomerGroup(): array;

    /**
     * Autogenerated description for setCustomerGroup() interface method
     *
     * @param string[] $value
     * @return void
     */
    public function setCustomerGroup(array $value): void;
}
