<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\PricingStorefrontApi\Api\Data;

/**
 * Autogenerated description for Status class
 *
 * phpcs:disable Magento2.PHP.FinalImplementation
 * @SuppressWarnings(PHPMD)
 * @SuppressWarnings(PHPCPD)
 */
final class Status implements StatusInterface
{

    /**
     * @var string
     */
    private $code;

    /**
     * @var string
     */
    private $message;
    
    /**
     * @inheritdoc
     *
     * @return string
     */
    public function getCode(): string
    {
        return (string) $this->code;
    }
    
    /**
     * @inheritdoc
     *
     * @param string $value
     * @return void
     */
    public function setCode(string $value): void
    {
        $this->code = $value;
    }
    
    /**
     * @inheritdoc
     *
     * @return string
     */
    public function getMessage(): string
    {
        return (string) $this->message;
    }
    
    /**
     * @inheritdoc
     *
     * @param string $value
     * @return void
     */
    public function setMessage(string $value): void
    {
        $this->message = $value;
    }
}
