<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\PricingStorefrontApi\Api\Data;

/**
 * Autogenerated description for Status interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface StatusInterface
{
    /**
     * Autogenerated description for getCode() interface method
     *
     * @return string
     */
    public function getCode(): string;

    /**
     * Autogenerated description for setCode() interface method
     *
     * @param string $value
     * @return void
     */
    public function setCode(string $value): void;

    /**
     * Autogenerated description for getMessage() interface method
     *
     * @return string
     */
    public function getMessage(): string;

    /**
     * Autogenerated description for setMessage() interface method
     *
     * @param string $value
     * @return void
     */
    public function setMessage(string $value): void;
}
