<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\PricingStorefrontApi\Api\Data;

/**
 * Autogenerated description for UnassignPricesRequest class
 *
 * phpcs:disable Magento2.PHP.FinalImplementation
 * @SuppressWarnings(PHPMD)
 * @SuppressWarnings(PHPCPD)
 */
final class UnassignPricesRequest implements UnassignPricesRequestInterface
{

    /**
     * @var array
     */
    private $ids;

    /**
     * @var string
     */
    private $priceBookId;
    
    /**
     * @inheritdoc
     *
     * @return string[]
     */
    public function getIds(): array
    {
        return (array) $this->ids;
    }
    
    /**
     * @inheritdoc
     *
     * @param string[] $value
     * @return void
     */
    public function setIds(array $value): void
    {
        $this->ids = $value;
    }
    
    /**
     * @inheritdoc
     *
     * @return string
     */
    public function getPriceBookId(): string
    {
        return (string) $this->priceBookId;
    }
    
    /**
     * @inheritdoc
     *
     * @param string $value
     * @return void
     */
    public function setPriceBookId(string $value): void
    {
        $this->priceBookId = $value;
    }
}
