<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\PricingStorefrontApi\Api\Data;

/**
 * Autogenerated description for UnassignPricesRequest interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface UnassignPricesRequestInterface
{
    /**
     * Autogenerated description for getIds() interface method
     *
     * @return string[]
     */
    public function getIds(): array;

    /**
     * Autogenerated description for setIds() interface method
     *
     * @param string[] $value
     * @return void
     */
    public function setIds(array $value): void;

    /**
     * Autogenerated description for getPriceBookId() interface method
     *
     * @return string
     */
    public function getPriceBookId(): string;

    /**
     * Autogenerated description for setPriceBookId() interface method
     *
     * @param string $value
     * @return void
     */
    public function setPriceBookId(string $value): void;
}
